INSERT INTO roles (id_role, role) VALUES (default, 'ROLE_ADMIN')
INSERT INTO roles (id_role, role) VALUES (default, 'ROLE_USER')

INSERT INTO academies VALUES (default, 'Pire', 'swingPire.png', 'Norena', 'Swing Pire', '666555444')
INSERT INTO academies VALUES (default, 'Vanesa', 'danzaVanesa.png', 'Gijon', 'Danza Vanessa', '611222333')
INSERT INTO academies VALUES (default, 'Niki', 'nikiDanceSkool.png', 'Gijon', 'Niki Dance Skool', '699888777')
INSERT INTO academies VALUES (default, 'Estela', 'bailestela.jpg', 'Torrelavega', 'Bailestela', '611999222')
INSERT INTO academies VALUES (default, 'May', 'mayDanceStudio.jpg', 'Fene', 'May Dance Studio', '699111888')
INSERT INTO academies VALUES (default, 'Patry', 'danceAcademy.png', 'Valencia', 'Dance Academy', '699111888')
INSERT INTO academies VALUES (default, 'Guille', 'evolution.jpg', 'Gerona', 'Evolution Dance', '699111888')
INSERT INTO academies VALUES (default, 'Jose', 'maestre.png', 'Lugo', 'Dance Academy', '699111888')
INSERT INTO academies VALUES (default, 'Jenny', 'urbanAcademy.png', 'Tarragona', 'Evolution Dance', '699111888')

INSERT INTO categories VALUES (default, 'Baby', '3-6')
INSERT INTO categories VALUES (default, 'Young Pro', '16-18')
INSERT INTO categories VALUES (default, 'Premium', 'Mayores de 30')
INSERT INTO categories VALUES (default, 'Absoluta', 'Mayores de 18')
INSERT INTO categories VALUES (default, 'Infantil Duo', '7-9')
INSERT INTO categories VALUES (default, 'Young Duo', '10-12')
INSERT INTO categories VALUES (default, 'Junior Duo', '8-10')
INSERT INTO categories VALUES (default, 'Duo Style', '13-18')


INSERT INTO groups VALUES (default, 'Urban Dancers', null, 1)
INSERT INTO groups VALUES (default, 'Breakers Junior', null, 5)
INSERT INTO groups VALUES (default, 'HipHop Kids', null, 4)
INSERT INTO groups VALUES (default, 'Funky Feet', null, 5)
INSERT INTO groups VALUES (default, 'Street Squad', null, 2)
INSERT INTO groups VALUES (default, 'Inzza Una Inzza', null, 3)

